---

- name: ensure apache is at the latest version
  yum: name=httpd state=latest
  become: true
  become_user: root
- name: write the apache config file
  template: src=httpd.j2 dest=/etc/httpd.conf
  become: true
  become_user: root
- name: restart apache
  service: name=httpd state=restarted
  become: true
  become_user: root
