---
- name: Creates directory
  file: path=~/apache_vm state=directory

- name: downloading vagrant
  action: "{{ ansible_pkg_mgr }} name=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm  state=present"
  become: yes

- name: install libvirt dependency
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
   - libvirt-devel
   - libxslt-devel
   - libxml2-devel
   - qemu-img
   - gcc
   - rsync
  become: yes

